#%RAML 1.0 NamedExample

value:
  courses:
      - 
        id: 1000
        name: Introduction to Programming
        hours: 23
        poc: asteanyng0@dion.ne.jp
      - 
        id: 1002
        name: Advanced JavaScript features
        hours: 36
        poc: briggulsford2@stanford.edu