#%RAML 1.0 NamedExample

value:
  ID: 66
  full_name: Santhosh Joseph
  location: Mysore
  country: India
  contact: 314 580 8028
  email: santhosh.joseph@infosys.com
  registration_date: 1/20/2018
  account: premium
