#%RAML 1.0 NamedExample

value:
  -
    ID: 66
    full_name: Santhosh Joseph
    location: Mysore
    country: India
    contact: 314 580 8028
    email: santhosh.joseph@infosys.com
    registration_date: 1/20/2018
    account: premium
  -
    ID: 67
    full_name: Tino Mathew
    location: Melbourne
    country: Australia
    contact: 124 654 9344
    email: tino.mathew@gmail.com
    registration_date: 2/12/2018
    account: regular