#%RAML 1.0 NamedExample

value:
  -
    full_name: Santhosh Joseph
    location: Mysore
    country: India
    contact: 314 580 8028
    email: santhosh.joseph@infosys.com
    account: premium
  -
    full_name: Tino Mathew
    location: Melbourne
    country: Australia
    contact: 124 654 9344
    email: tino.mathew@gmail.com
    account: regular